In [1]:
# Импорт библиотек
import numpy
import pandas as pd


In [2]:
# Импорт matplotlib - не нужен, на всякий случай

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

In [3]:
# Задаем рабочую папку

import os
os.chdir("C:/Users/USER/Documents/Python/_Python_part_2/Lecture_2_01")


In [4]:
# Импорт нужного из keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils


C:\Users\USER\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
# Импорт обучающей выборки
wine = pd.read_csv('Wine.txt', sep='\t', header=0)


In [6]:
wine.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0   14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1   13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2   13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3   14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4   13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   

   Input10  Input11  Input12  Input13  Desired1(3)  
0     5.64     1.04     3.92     1065            0  
1     4.38     1.05     3.40     1050            0  
2     5.68     1.03     3.17     1185            0  
3     7.80     0.86     3.45     1480            0  
4     4.32     1.04     2.93      735            0

In [7]:
wine['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [8]:
#  предикторы и отклик разделяем
# Отклик - группирующая переменная -  вектор y
y = wine['Desired1(3)']
# Предикторы - таблица X
X = wine.drop('Desired1(3)', axis=1)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12345,
                                                    # доля объёма тестового множества
                                                    test_size=0.33)

In [10]:
X_train.head()
X_test.head()
y_train.head()
y_test.head()




109    2
68     2
176    1
55     0
149    1
Name: Desired1(3), dtype: int64

In [11]:
#  Преобразование pandas dataframe в numpy array
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values



In [12]:
# Больше 2-х классов
# Классы не упорядочены
y_train_bin = np_utils.to_categorical(y_train)

y_test_bin = np_utils.to_categorical(y_test)

In [13]:
# Почему не работает?
y_train_bin.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [14]:
y_train_bin[0:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [15]:
from keras.models import Sequential
from keras.layers import Dense


In [20]:

# Creating a model
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu'))
model.add(Dense(10, activation='relu', ))
model.add(Dense(3, activation='softmax'))


# Compiling model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 0s 3ms/step - loss: 4.5434 - acc: 0.6639
Epoch 2/300
119/119 [==============================] - 0s 227us/step - loss: 4.5532 - acc: 0.6639
Epoch 3/300
119/119 [==============================] - 0s 218us/step - loss: 4.5990 - acc: 0.6807
Epoch 4/300
119/119 [==============================] - 0s 202us/step - loss: 4.5408 - acc: 0.6555
Epoch 5/300
119/119 [==============================] - 0s 193us/step - loss: 4.5615 - acc: 0.6555
Epoch 6/300
119/119 [==============================] - 0s 202us/step - loss: 4.6278 - acc: 0.6555
Epoch 7/300
119/119 [==============================] - 0s 218us/step - loss: 4.4853 - acc: 0.6723
Epoch 8/300
119/119 [==============================] - 0s 151us/step - loss: 4.5290 - acc: 0.6639
Epoch 9/300
119/119 [==============================] - 0s 235us/step - loss: 4.6217 - acc: 0.6639
Epoch 10/300
119/119 [==============================] - 0s 210us/step - loss: 4.6062 - acc: 0.6555
Epoch 11/300
119/119 

119/119 [==============================] - 0s 151us/step - loss: 4.5053 - acc: 0.6891
Epoch 84/300
119/119 [==============================] - 0s 143us/step - loss: 4.4967 - acc: 0.6891
Epoch 85/300
119/119 [==============================] - 0s 143us/step - loss: 4.5133 - acc: 0.6723
Epoch 86/300
119/119 [==============================] - 0s 244us/step - loss: 4.5134 - acc: 0.6975
Epoch 87/300
119/119 [==============================] - 0s 143us/step - loss: 4.5533 - acc: 0.6639
Epoch 88/300
119/119 [==============================] - 0s 143us/step - loss: 4.5215 - acc: 0.6639
Epoch 89/300
119/119 [==============================] - 0s 227us/step - loss: 4.6219 - acc: 0.6639
Epoch 90/300
119/119 [==============================] - 0s 227us/step - loss: 4.6119 - acc: 0.6807
Epoch 91/300
119/119 [==============================] - 0s 227us/step - loss: 4.4962 - acc: 0.6807
Epoch 92/300
119/119 [==============================] - 0s 252us/step - loss: 4.5015 - acc: 0.6807
Epoch 93/300
119/119 [=

119/119 [==============================] - 0s 193us/step - loss: 4.4971 - acc: 0.6891
Epoch 166/300
119/119 [==============================] - 0s 143us/step - loss: 4.6670 - acc: 0.6218
Epoch 167/300
119/119 [==============================] - 0s 143us/step - loss: 4.4930 - acc: 0.6975
Epoch 168/300
119/119 [==============================] - 0s 176us/step - loss: 4.6022 - acc: 0.6723
Epoch 169/300
119/119 [==============================] - 0s 185us/step - loss: 4.6392 - acc: 0.6387
Epoch 170/300
119/119 [==============================] - 0s 151us/step - loss: 4.6300 - acc: 0.6387
Epoch 171/300
119/119 [==============================] - 0s 210us/step - loss: 4.4700 - acc: 0.6807
Epoch 172/300
119/119 [==============================] - 0s 286us/step - loss: 4.4625 - acc: 0.6807
Epoch 173/300
119/119 [==============================] - 0s 202us/step - loss: 4.5068 - acc: 0.6807
Epoch 174/300
119/119 [==============================] - 0s 202us/step - loss: 4.4855 - acc: 0.6891
Epoch 175/300


119/119 [==============================] - 0s 143us/step - loss: 4.4476 - acc: 0.7059
Epoch 247/300
119/119 [==============================] - 0s 143us/step - loss: 4.4279 - acc: 0.7059
Epoch 248/300
119/119 [==============================] - 0s 210us/step - loss: 4.4161 - acc: 0.6975
Epoch 249/300
119/119 [==============================] - 0s 151us/step - loss: 4.4437 - acc: 0.7059
Epoch 250/300
119/119 [==============================] - 0s 227us/step - loss: 4.4879 - acc: 0.6891
Epoch 251/300
119/119 [==============================] - 0s 185us/step - loss: 4.4353 - acc: 0.6807
Epoch 252/300
119/119 [==============================] - 0s 210us/step - loss: 4.4174 - acc: 0.7059
Epoch 253/300
119/119 [==============================] - 0s 219us/step - loss: 4.4489 - acc: 0.6723
Epoch 254/300
119/119 [==============================] - 0s 185us/step - loss: 4.4382 - acc: 0.6975
Epoch 255/300
119/119 [==============================] - 0s 244us/step - loss: 4.4309 - acc: 0.6891
Epoch 256/300


In [21]:
# evaluate the model
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 1ms/step

Accuracy: 59.32%


In [18]:
# calculate predictions
predictions = model.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [19]:
print(predictions[0:5])

[[3.0074161e-01 0.0000000e+00 6.9925833e-01]
 [2.2982089e-01 0.0000000e+00 7.7017915e-01]
 [5.7817298e-01 0.0000000e+00 4.2182696e-01]
 [9.9435896e-01 0.0000000e+00 5.6410097e-03]
 [1.9473886e-02 1.7381439e-36 9.8052615e-01]]
