In [1]:
# Импорт библиотек
import numpy as np
import pandas as pd

# Импорт matplotlib - не нужен, на всякий случай

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

In [2]:
# Импорт нужного из keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

from keras import optimizers
from keras import initializers

C:\Users\USER\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
# Задаем рабочую папку

import os
os.chdir("C:/Users/USER/Documents/Python/_AD_Python_part_4_NNet/01_NNet_Basics")


In [4]:
# Импорт обучающей выборки
zzz = pd.read_csv('data_XOR.txt', sep=',', header=0)


In [5]:
# zzz.head()

print(zzz)

   x1  x2  Y
0   1   1  0
1   0   0  0
2   0   1  1
3   1   0  1


In [6]:
#  Вариант
# Создаю обучающую выборку
#  zzz = pd.DataFrame({ 'x1' : [0, 0, 1., 1.], 
#                       'x2' : [0, 1., 0, 1.],
#                        'Y' : [0, 1., 1., 0] })


In [7]:
zzz.columns

Index(['x1', 'x2', 'Y'], dtype='object')

In [8]:
type(zzz)

pandas.core.frame.DataFrame

In [9]:
#  предикторы и отклик разделяем
# Отклик - группирующая переменная -  вектор y
y = zzz['Y']
# Предикторы - таблица X
X = zzz.drop('Y', axis=1)

In [10]:
np.random.seed(1234)

In [19]:
i = 2015

i

2015

In [20]:
i = i + 1

# init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.5, seed=i)

init_2 = initializers.TruncatedNormal(mean=0.0, stddev=5, seed=i)
init_3 = initializers.Constant(value = 1e-3)

# Creating a model
model = Sequential()
model.add(Dense(4, input_dim=2, activation='sigmoid', kernel_initializer=init_2, bias_initializer=init_3))
model.add(Dense(1, activation='sigmoid', kernel_initializer=init_2, bias_initializer=init_3))

sgd = optimizers.SGD(lr=0.1)


# Compiling model

#  долгий поиск решения
# model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])

#  быстрый поиск решения
model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['accuracy'])



In [21]:
# Training a model
model.fit(X, y, epochs=5000, batch_size=4, verbose = 0)

#  evaluate the model
scores = model.evaluate(X, y)
print("\nAccuracy: %.2f%%" % (scores[1]*100))
#  print('i=',  i, scores)

predictions = model.predict(X)

rounded = [round(x[0], 3) for x in predictions]
print('i=',  i, rounded)




4/4 [==============================] - 0s 18ms/step

Accuracy: 100.00%
i= 2016 [0.236, 0.014, 0.805, 0.849]


In [22]:
scores

[0.02909643016755581, 1.0]

In [ ]:
i = 2015

i

In [60]:
#  Объединяю две предыдущие ячейки

while True:
    i = i + 1

    # init_2 = initializers.TruncatedNormal(mean=0.0, stddev=0.5, seed=i)
    init_2 = initializers.TruncatedNormal(mean=0.0, stddev=5, seed=i)

    # Creating a model
    model = Sequential()
    model.add(Dense(4, input_dim=2, activation='sigmoid', kernel_initializer=init_2, bias_initializer=init_3))
    # model.add(Dense(2, input_dim=2, activation='sigmoid', kernel_initializer=init_2, bias_initializer=init_3))
    model.add(Dense(1, activation='sigmoid', kernel_initializer=init_2, bias_initializer=init_3))

    # Compiling model
    # model.compile(loss='mean_squared_error', optimizer='SGD', metrics=['accuracy'])
    # model.compile(loss='mean_squared_error', optimizer='Adam', metrics=['accuracy'])
    model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])

    # Training a model
    model.fit(X, y, epochs=8000, batch_size=4, verbose = 0)

    # evaluate the model
    scores = model.evaluate(X, y)
    print('i=',  i, scores)
    if scores[1]>0.75:
        break

print("\nAccuracy: %.2f%%" % (scores[1]*100))

predictions = model.predict(X)

rounded = [round(x[0], 3) for x in predictions]
print(rounded)

4/4 [==============================] - 0s 18ms/step
i= 2019 [0.2629818916320801, 0.75]
4/4 [==============================] - 0s 21ms/step
i= 2020 [0.250297486782074, 0.75]
4/4 [==============================] - 0s 18ms/step
i= 2021 [0.14733995497226715, 0.5]
4/4 [==============================] - 0s 20ms/step
i= 2022 [0.2568129003047943, 0.75]
4/4 [==============================] - 0s 27ms/step
i= 2023 [0.1373118907213211, 0.75]
4/4 [==============================] - 0s 28ms/step
i= 2024 [0.14670097827911377, 0.75]
4/4 [==============================] - 0s 25ms/step
i= 2025 [0.2517770528793335, 0.75]
4/4 [==============================] - 0s 54ms/step
i= 2026 [0.294234037399292, 0.75]
4/4 [==============================] - 0s 31ms/step
i= 2027 [0.23785394430160522, 0.75]
4/4 [==============================] - 0s 46ms/step
i= 2028 [0.25082823634147644, 0.75]
4/4 [==============================] - 0s 36ms/step
i= 2029 [0.253478080034256, 0.75]
4/4 [==============================] - 0s 3

4/4 [==============================] - 1s 189ms/step
i= 2113 [0.2463568150997162, 0.75]
4/4 [==============================] - 1s 193ms/step
i= 2114 [0.15810655057430267, 0.75]
4/4 [==============================] - 1s 249ms/step
i= 2115 [0.49992993474006653, 0.5]
4/4 [==============================] - 1s 201ms/step
i= 2116 [0.1318291574716568, 0.5]
4/4 [==============================] - 1s 202ms/step
i= 2117 [0.1343003213405609, 0.75]
4/4 [==============================] - 1s 204ms/step
i= 2118 [0.3615337014198303, 0.5]
4/4 [==============================] - 1s 289ms/step
i= 2119 [0.14317351579666138, 0.75]
4/4 [==============================] - 1s 202ms/step
i= 2120 [0.5045759677886963, 0.5]
4/4 [==============================] - 1s 214ms/step
i= 2121 [0.1440214365720749, 0.5]
4/4 [==============================] - 1s 206ms/step
i= 2122 [0.20901475846767426, 0.75]
4/4 [==============================] - 1s 206ms/step
i= 2123 [0.1509130597114563, 0.75]
4/4 [============================

KeyboardInterrupt: 

In [16]:

# Creating a model
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu'))
model.add(Dense(10, activation='relu', ))
model.add(Dense(3, activation='softmax'))


# Compiling model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 0s 2ms/step - loss: 5.1846 - acc: 0.5714
Epoch 2/300
119/119 [==============================] - 0s 202us/step - loss: 4.6744 - acc: 0.6303
Epoch 3/300
119/119 [==============================] - 0s 143us/step - loss: 4.7224 - acc: 0.6134
Epoch 4/300
119/119 [==============================] - 0s 210us/step - loss: 4.6490 - acc: 0.6218
Epoch 5/300
119/119 [==============================] - 0s 159us/step - loss: 4.7271 - acc: 0.6134
Epoch 6/300
119/119 [==============================] - 0s 168us/step - loss: 4.7002 - acc: 0.6471
Epoch 7/300
119/119 [==============================] - 0s 261us/step - loss: 4.6301 - acc: 0.6134
Epoch 8/300
119/119 [==============================] - 0s 252us/step - loss: 4.6719 - acc: 0.6218
Epoch 9/300
119/119 [==============================] - 0s 177us/step - loss: 4.6948 - acc: 0.6218
Epoch 10/300
119/119 [==============================] - 0s 185us/step - loss: 4.6424 - acc: 0.6303
Epoch 11/300
119/119 

119/119 [==============================] - 0s 134us/step - loss: 4.4915 - acc: 0.6639
Epoch 165/300
119/119 [==============================] - 0s 168us/step - loss: 4.4971 - acc: 0.6723
Epoch 166/300
119/119 [==============================] - 0s 159us/step - loss: 4.5208 - acc: 0.6555
Epoch 167/300
119/119 [==============================] - 0s 176us/step - loss: 4.5144 - acc: 0.6639
Epoch 168/300
119/119 [==============================] - 0s 176us/step - loss: 4.4632 - acc: 0.6807
Epoch 169/300
119/119 [==============================] - 0s 176us/step - loss: 4.4705 - acc: 0.6639
Epoch 170/300
119/119 [==============================] - 0s 202us/step - loss: 4.4614 - acc: 0.6639
Epoch 171/300
119/119 [==============================] - 0s 269us/step - loss: 4.4643 - acc: 0.6639
Epoch 172/300
119/119 [==============================] - 0s 202us/step - loss: 4.4618 - acc: 0.6639
Epoch 173/300
119/119 [==============================] - 0s 202us/step - loss: 4.4750 - acc: 0.6555
Epoch 174/300


119/119 [==============================] - 0s 168us/step - loss: 4.4502 - acc: 0.6807
Epoch 247/300
119/119 [==============================] - 0s 143us/step - loss: 4.4595 - acc: 0.6723
Epoch 248/300
119/119 [==============================] - 0s 135us/step - loss: 4.4463 - acc: 0.6891
Epoch 249/300
119/119 [==============================] - 0s 193us/step - loss: 4.4603 - acc: 0.6723
Epoch 250/300
119/119 [==============================] - 0s 126us/step - loss: 4.4531 - acc: 0.6807
Epoch 251/300
119/119 [==============================] - 0s 134us/step - loss: 4.4609 - acc: 0.6723
Epoch 252/300
119/119 [==============================] - 0s 160us/step - loss: 4.4670 - acc: 0.6639
Epoch 253/300
119/119 [==============================] - 0s 168us/step - loss: 4.4558 - acc: 0.6975
Epoch 254/300
119/119 [==============================] - 0s 193us/step - loss: 4.4497 - acc: 0.6639
Epoch 255/300
119/119 [==============================] - 0s 176us/step - loss: 4.4490 - acc: 0.6891
Epoch 256/300


In [17]:
# evaluate the model
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 983us/step

Accuracy: 62.71%


In [18]:
# calculate predictions
predictions = model.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [19]:
print(predictions[0:5])

[[3.0074161e-01 0.0000000e+00 6.9925833e-01]
 [2.2982089e-01 0.0000000e+00 7.7017915e-01]
 [5.7817298e-01 0.0000000e+00 4.2182696e-01]
 [9.9435896e-01 0.0000000e+00 5.6410097e-03]
 [1.9473886e-02 1.7381439e-36 9.8052615e-01]]
