In [1]:
# Импорт библиотек
import numpy as np
import pandas as pd

# Импорт matplotlib - не нужен, на всякий случай

import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline


In [2]:
# Импорт нужного из keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils



C:\Users\USER\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
# Задаем рабочую папку

import os
os.chdir("C:/Users/USER/Documents/Python/_AD_Python_part_4_NNet/03_NNet_Classification")


In [4]:
# Импорт данных
wine = pd.read_csv('Wine.txt', sep='\t', header=0)


In [5]:
#  Все хорошо?
wine.head()

Input1  Input2  Input3  Input4  Input5  Input6  Input7  Input8  Input9  \
0   14.23    1.71    2.43    15.6     127    2.80    3.06    0.28    2.29   
1   13.20    1.78    2.14    11.2     100    2.65    2.76    0.26    1.28   
2   13.16    2.36    2.67    18.6     101    2.80    3.24    0.30    2.81   
3   14.37    1.95    2.50    16.8     113    3.85    3.49    0.24    2.18   
4   13.24    2.59    2.87    21.0     118    2.80    2.69    0.39    1.82   

   Input10  Input11  Input12  Input13  Desired1(3)  
0     5.64     1.04     3.92     1065            0  
1     4.38     1.05     3.40     1050            0  
2     5.68     1.03     3.17     1185            0  
3     7.80     0.86     3.45     1480            0  
4     4.32     1.04     2.93      735            0

In [6]:
#  Отклик сбалансирован?
wine['Desired1(3)'].value_counts(normalize=True)

2    0.398876
0    0.331461
1    0.269663
Name: Desired1(3), dtype: float64

In [7]:
#   Разделяем предикторы и отклик
# Отклик - группирующая переменная -  вектор y
y = wine['Desired1(3)']
# Предикторы - таблица X
X = wine.drop('Desired1(3)', axis=1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=12345,
                                                    # доля объёма тестового множества
                                                    test_size=0.33)

In [9]:

#  Все хорошо?
X_train.head()
X_test.head()
y_train.head()
y_test.head()



109    2
68     2
176    1
55     0
149    1
Name: Desired1(3), dtype: int64

In [10]:
#  Преобразование pandas dataframe в numpy array
X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values



In [11]:
# Больше 2-х классов
# Классы не упорядочены
y_train_bin = np_utils.to_categorical(y_train)

y_test_bin = np_utils.to_categorical(y_test)

In [13]:
# Почему не работает?
y_train_bin.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [12]:
y_train_bin[0:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [13]:

# Creating a model
model = Sequential()
model.add(Dense(9, input_dim=13, activation='relu'))
model.add(Dense(10, activation='relu', ))
model.add(Dense(3, activation='softmax'))


# Compiling model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Training a model
model.fit(X_train, y_train_bin, epochs=300, batch_size=10)


Epoch 1/300
119/119 [==============================] - 0s 4ms/step - loss: 10.3940 - acc: 0.3277
Epoch 2/300
119/119 [==============================] - 0s 143us/step - loss: 9.5756 - acc: 0.3697
Epoch 3/300
119/119 [==============================] - 0s 244us/step - loss: 4.2582 - acc: 0.5966
Epoch 4/300
119/119 [==============================] - 0s 210us/step - loss: 2.1032 - acc: 0.6723
Epoch 5/300
119/119 [==============================] - 0s 176us/step - loss: 1.7196 - acc: 0.7059
Epoch 6/300
119/119 [==============================] - 0s 303us/step - loss: 1.8194 - acc: 0.6807
Epoch 7/300
119/119 [==============================] - 0s 210us/step - loss: 1.5577 - acc: 0.6975
Epoch 8/300
119/119 [==============================] - 0s 168us/step - loss: 1.5291 - acc: 0.6555
Epoch 9/300
119/119 [==============================] - 0s 252us/step - loss: 1.4438 - acc: 0.6975
Epoch 10/300
119/119 [==============================] - 0s 202us/step - loss: 1.3259 - acc: 0.6555
Epoch 11/300
119/119

119/119 [==============================] - 0s 193us/step - loss: 0.1590 - acc: 0.9664
Epoch 166/300
119/119 [==============================] - 0s 160us/step - loss: 0.2317 - acc: 0.8992
Epoch 167/300
119/119 [==============================] - 0s 210us/step - loss: 0.1672 - acc: 0.9496
Epoch 168/300
119/119 [==============================] - 0s 151us/step - loss: 0.1755 - acc: 0.9580
Epoch 169/300
119/119 [==============================] - 0s 202us/step - loss: 0.1397 - acc: 0.9496
Epoch 170/300
119/119 [==============================] - 0s 193us/step - loss: 0.1550 - acc: 0.9328
Epoch 171/300
119/119 [==============================] - 0s 193us/step - loss: 0.1302 - acc: 0.9580
Epoch 172/300
119/119 [==============================] - 0s 210us/step - loss: 0.1732 - acc: 0.9328
Epoch 173/300
119/119 [==============================] - 0s 277us/step - loss: 0.2854 - acc: 0.9244
Epoch 174/300
119/119 [==============================] - 0s 210us/step - loss: 0.2118 - acc: 0.8992
Epoch 175/300


119/119 [==============================] - 0s 261us/step - loss: 0.1416 - acc: 0.9412
Epoch 248/300
119/119 [==============================] - 0s 202us/step - loss: 0.1035 - acc: 0.9580
Epoch 249/300
119/119 [==============================] - ETA: 0s - loss: 0.0525 - acc: 1.000 - 0s 210us/step - loss: 0.1430 - acc: 0.9244
Epoch 250/300
119/119 [==============================] - 0s 202us/step - loss: 0.1070 - acc: 0.9664
Epoch 251/300
119/119 [==============================] - 0s 235us/step - loss: 0.1027 - acc: 0.9580
Epoch 252/300
119/119 [==============================] - 0s 269us/step - loss: 0.1193 - acc: 0.9664
Epoch 253/300
119/119 [==============================] - 0s 261us/step - loss: 0.1225 - acc: 0.9580
Epoch 254/300
119/119 [==============================] - 0s 218us/step - loss: 0.1240 - acc: 0.9496
Epoch 255/300
119/119 [==============================] - 0s 219us/step - loss: 0.1186 - acc: 0.9580
Epoch 256/300
119/119 [==============================] - 0s 252us/step - los

In [14]:
# evaluate the model
scores = model.evaluate(X_test, y_test_bin)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

59/59 [==============================] - 0s 2ms/step

Accuracy: 88.14%


In [15]:
# calculate predictions
predictions = model.predict(X_test)
# round predictions
# rounded = [round(x[0]) for x in predictions]
# print(rounded)

In [16]:
print(predictions[0:5])

[[1.5805641e-01 1.2223081e-04 8.4182131e-01]
 [5.2375352e-01 2.4471879e-01 2.3152776e-01]
 [6.8709161e-04 9.9930882e-01 4.0230107e-06]
 [9.9867415e-01 1.1057894e-03 2.2017909e-04]
 [2.2182623e-05 9.9995279e-01 2.5008236e-05]]
